#!/usr/bin/env python3
"""
CryoSPARC Tools script that combines denoised micrographs from multiple
matching exposure outputs by taking the pixelwise minimum at each pixel.

The script:

- loads one exposure output from each denoising job
- auto-detects a denoised slot on each source unless --denoised-slot is given
- validates that all source outputs describe the same micrograph UIDs
- optionally high-pass filters each source image before the minimum consensus
- reads the denoised image for each matching micrograph from every source
- writes a new MRC whose pixels are the minimum across the source images
- saves a derived exposure output whose denoised slot points at the new MRCs
  while the remaining slots are preserved from the first source output

Notes:
- the first source is used as the passthrough reference dataset
- the script assumes it runs on a machine that can read and write the
  CryoSPARC project directory
"""

from __future__ import annotations

import argparse
import math
import importlib
import json
import re
import sys
import time
import warnings
from io import BytesIO
from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Dict, List, Optional, Sequence, Tuple

try:
    import numpy as np
except ImportError:
    np = None


class HelpFormatter(argparse.ArgumentDefaultsHelpFormatter, argparse.RawDescriptionHelpFormatter):
    pass


DEFAULT_DENOISED_SLOT = "micrograph_blob_denoised"


@dataclass
class SourceDataset:
    job_uid: str
    output_name: str
    slot_name: str
    dataset: object
    uid_to_row: Dict[int, int]

    @property
    def label(self) -> str:
        return f"{self.job_uid}:{self.output_name} [{self.slot_name}]"


@dataclass
class PreparedSource:
    label: str
    slot_name: str
    uid_to_row: Dict[int, int]
    paths: List[str]
    idxs: Optional[np.ndarray]
    shapes: Optional[np.ndarray]
    slot_psizes: Optional[np.ndarray]
    mscope_psizes: Optional[np.ndarray]


@dataclass
class ProcessedMicrograph:
    output_index: int
    output_rel_path: str
    combined_shape: Tuple[int, int]
    combined_psize_A: float
    combined_vmin: float
    combined_vmax: float
    preview_image: Optional[np.ndarray] = None




def build_job_title(base_title: str, source_count: int, highpass_resolution_A: Optional[float], highpass_mode: str, clahe: bool, clahe_clip_limit: float) -> str:
    parts = [base_title.strip() or "Consensus denoised micrographs", f"n={int(source_count)}"]
    if highpass_resolution_A is not None:
        parts.append(f"HP {float(highpass_resolution_A):g}A {normalize_text(highpass_mode)}")
    else:
        parts.append("no HP")
    if clahe:
        parts.append(f"CLAHE clip={float(clahe_clip_limit):g}")
    return " | ".join(parts)


def build_job_description(args: argparse.Namespace, prepared_sources: Sequence[PreparedSource], reference_source: SourceDataset, output_slot_name: str, micrograph_count: int) -> str:
    lines = [
        "Consensus denoised micrographs generated by pixelwise minimum across source denoised images.",
        "",
        f"Reference source: {args.project_uid}/{reference_source.job_uid}:{reference_source.output_name} [{reference_source.slot_name}]",
        f"Output slot: {output_slot_name}",
        f"Micrographs: {int(micrograph_count):,}",
        f"Sources: {len(prepared_sources)}",
        f"Workers: {int(args.workers)}",
    ]
    if args.highpass is not None:
        lines.append(f"High-pass: {float(args.highpass):g} A ({normalize_text(args.highpass_mode)})")
    else:
        lines.append("High-pass: disabled")
    if args.clahe:
        lines.append(f"CLAHE: enabled (clip_limit={float(args.clahe_clip_limit):g}, kernel_size={args.clahe_kernel_size if args.clahe_kernel_size else 'auto'})")
    else:
        lines.append("CLAHE: disabled")
    lines.append("")
    lines.append("Source jobs:")
    for idx, src in enumerate(prepared_sources, start=1):
        lines.append(f"- {idx}. {src.label}")
    return "\n".join(lines)


def create_preview_figure(image: np.ndarray, title: str):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    finite = np.asarray(image, dtype=np.float32)
    finite_mask = np.isfinite(finite)
    if np.any(finite_mask):
        values = finite[finite_mask]
        vmin = float(np.percentile(values, 1.0))
        vmax = float(np.percentile(values, 99.0))
        if not np.isfinite(vmin) or not np.isfinite(vmax) or vmax <= vmin:
            vmin = float(np.min(values))
            vmax = float(np.max(values))
    else:
        vmin, vmax = 0.0, 1.0
    fig, ax = plt.subplots(figsize=(6, 6), dpi=150)
    ax.imshow(finite, cmap='gray', vmin=vmin, vmax=vmax, interpolation='nearest')
    ax.set_title(title)
    ax.set_xticks([])
    ax.set_yticks([])
    fig.tight_layout()
    return fig


def log_preview_image(external_job, image: np.ndarray, title: str, name: str = "preview_first_micrograph") -> None:
    fig = create_preview_figure(image, title)
    try:
        if hasattr(external_job, '_upload_plot'):
            assets = external_job._upload_plot(fig, name=name, formats=['png'], savefig_kw=dict(bbox_inches='tight', pad_inches=0))
            if assets:
                try:
                    external_job.set_tile_image(assets[0])
                except Exception:
                    pass
                external_job.log(f"Logged preview image '{name}' and set job thumbnail.")
                return
        if hasattr(external_job, 'log_plot'):
            try:
                external_job.log_plot(fig, text=title)
                external_job.log(f"Logged preview image '{name}'.")
                return
            except TypeError:
                external_job.log_plot(fig)
                external_job.log(f"Logged preview image '{name}'.")
                return
        buffer = BytesIO()
        fig.savefig(buffer, format='png', bbox_inches='tight', pad_inches=0)
        external_job.log(f"Preview image generated for first denoised micrograph ({name}), but this cryosparc-tools version does not expose plot logging helpers.")
    finally:
        try:
            import matplotlib.pyplot as plt
            plt.close(fig)
        except Exception:
            pass

def ensure_prefix(value: str, prefix: str) -> str:
    return value if value.startswith(prefix) else f"{prefix}{value}"


def normalize_text(value) -> str:
    if isinstance(value, bytes):
        return value.decode("utf-8")
    if np is not None and isinstance(value, np.bytes_):
        return value.decode("utf-8")
    return str(value)


def check_runtime_dependencies(args=None) -> None:
    missing: List[Tuple[str, str, str]] = []
    if np is None:
        missing.append(("numpy", "Required for array math.", "pip install numpy"))
    for module_name, reason, install_hint in (
        ("mrcfile", "Required for reading and writing MRC files.", "pip install mrcfile"),
        ("cryosparc.tools", "Required for connecting to CryoSPARC.", "pip install cryosparc-tools"),
    ):
        try:
            importlib.import_module(module_name)
        except ImportError:
            missing.append((module_name, reason, install_hint))

    if args is not None and getattr(args, "highpass", None) is not None and getattr(args, "highpass_mode", "gaussian_fft") == "gaussian_subtract":
        try:
            importlib.import_module("scipy.ndimage")
        except ImportError:
            missing.append((
                "scipy.ndimage",
                "Required when using --highpass-mode gaussian_subtract.",
                "pip install scipy",
            ))

    if args is not None and getattr(args, "clahe", False):
        try:
            importlib.import_module("skimage.exposure")
        except ImportError:
            missing.append((
                "skimage.exposure",
                "Required when using --clahe.",
                "pip install scikit-image",
            ))

    if missing:
        lines = [
            "Missing dependencies for consensus_denoise.py.",
            "Install the packages below in the same environment where you run this script, then rerun the command:",
            "",
        ]
        for module_name, reason, install_hint in missing:
            lines.append(f"- {module_name}: {reason}")
            lines.append(f"  Suggested fix: {install_hint}")
        raise RuntimeError("\n".join(lines))

    if sys.version_info < (3, 8):
        raise RuntimeError(
            "consensus_denoise.py requires Python 3.8 or newer. "
            f"Current interpreter: {sys.version.split()[0]}"
        )


def existing_field(dataset, field: str) -> bool:
    try:
        dataset[field]
        return True
    except Exception:
        return False


def require_field(dataset, field: str) -> None:
    if not existing_field(dataset, field):
        raise KeyError(f"Required dataset field is missing: {field}")


def array_copy(dataset, field: str) -> np.ndarray:
    return np.array(dataset[field], copy=True)


def read_mrc_image(path: Path, stack_index: int = 0) -> Tuple[np.ndarray, Optional[float]]:
    import mrcfile

    with mrcfile.mmap(path, mode="r", permissive=True) as handle:
        data = handle.data
        voxel_x = float(handle.voxel_size.x) if handle.voxel_size.x else 0.0
        if data.ndim == 2:
            if int(stack_index) not in (0, -1):
                raise IndexError(f"Stack index {stack_index} is invalid for single-image file {path}")
            image = np.array(data, dtype=np.float32, copy=True)
        elif data.ndim == 3:
            if int(stack_index) < 0 or int(stack_index) >= int(data.shape[0]):
                raise IndexError(f"Stack index {stack_index} is out of range for {path} with {data.shape[0]} image(s)")
            image = np.array(data[int(stack_index)], dtype=np.float32, copy=True)
        else:
            raise ValueError(f"Unsupported MRC dimensionality for {path}: {data.shape}")
    return image, (voxel_x if voxel_x > 0 else None)


def write_mrc(path: Path, data: np.ndarray, voxel_size_angstrom: float) -> None:
    import mrcfile

    path.parent.mkdir(parents=True, exist_ok=True)
    with mrcfile.new(path, overwrite=True) as handle:
        handle.set_data(np.asarray(data, dtype=np.float32))
        handle.voxel_size = float(voxel_size_angstrom)
        handle.update_header_stats()


def _highpass_cutoff_info(pixel_size_A: float, resolution_A: Optional[float]) -> Optional[Tuple[float, float]]:
    if resolution_A is None or float(resolution_A) <= 0.0 or float(pixel_size_A) <= 0.0:
        return None
    cutoff = 1.0 / float(resolution_A)
    nyquist = 1.0 / (2.0 * float(pixel_size_A))
    if cutoff <= 0.0 or cutoff >= nyquist:
        return None
    return float(cutoff), float(nyquist)


def apply_clahe(
    image: np.ndarray,
    clip_limit: float = 0.01,
    kernel_size: Optional[int] = None,
) -> np.ndarray:
    image = np.asarray(image, dtype=np.float32)
    finite = np.isfinite(image)
    if not np.any(finite):
        return image
    valid = image[finite]
    lo = float(np.min(valid))
    hi = float(np.max(valid))
    if not np.isfinite(lo) or not np.isfinite(hi) or hi <= lo:
        return image
    scaled = (image - lo) / (hi - lo)
    scaled = np.clip(scaled, 0.0, 1.0)
    try:
        from skimage.exposure import equalize_adapthist
    except Exception as exc:
        raise RuntimeError(
                'CLAHE requested but scikit-image is not installed. Install it with: pip install scikit-image'
            ) from exc
    if kernel_size is not None and int(kernel_size) > 0:
        ks = int(kernel_size)
    else:
        min_dim = max(1, int(min(image.shape)))
        ks = max(32, min(256, min_dim // 8))
    enhanced = equalize_adapthist(scaled, kernel_size=ks, clip_limit=float(clip_limit))
    restored = lo + np.asarray(enhanced, dtype=np.float32) * (hi - lo)
    return np.asarray(restored, dtype=np.float32)


def smooth_highpass_filter(
    image: np.ndarray,
    pixel_size_A: float,
    resolution_A: Optional[float],
    mode: str = "gaussian_fft",
) -> np.ndarray:
    image = np.asarray(image, dtype=np.float32)
    info = _highpass_cutoff_info(pixel_size_A=float(pixel_size_A), resolution_A=resolution_A)
    if info is None:
        return image
    cutoff, nyquist = info

    mode_normalized = str(mode).strip().lower()
    if mode_normalized in {"cosine", "hann", "raised_cosine"}:
        fy = np.fft.fftfreq(image.shape[0], d=float(pixel_size_A))
        fx = np.fft.rfftfreq(image.shape[1], d=float(pixel_size_A))
        radius = np.sqrt(fy[:, None] ** 2 + fx[None, :] ** 2)

        transition_fraction = 0.15
        low_edge = cutoff * max(0.0, 1.0 - transition_fraction)
        high_edge = min(nyquist, cutoff * (1.0 + transition_fraction))

        response = np.ones_like(radius, dtype=np.float32)
        if high_edge <= low_edge:
            response[radius < cutoff] = 0.0
        else:
            response[radius <= low_edge] = 0.0
            mid = (radius > low_edge) & (radius < high_edge)
            response[mid] = 0.5 * (
                1.0 - np.cos(np.pi * (radius[mid] - low_edge) / (high_edge - low_edge))
            )

        filtered_fft = np.fft.rfftn(image) * response
        filtered = np.fft.irfftn(filtered_fft, s=image.shape).real
        return np.asarray(filtered, dtype=np.float32)

    if mode_normalized in {"gaussian_fft", "gaussian-frequency", "gaussian_frequency"}:
        fy = np.fft.fftfreq(image.shape[0], d=float(pixel_size_A))
        fx = np.fft.rfftfreq(image.shape[1], d=float(pixel_size_A))
        radius = np.sqrt(fy[:, None] ** 2 + fx[None, :] ** 2)
        sigma_f = cutoff / math.sqrt(2.0 * math.log(2.0))
        lowpass = np.exp(-0.5 * (radius / max(sigma_f, 1e-12)) ** 2)
        response = 1.0 - lowpass
        filtered_fft = np.fft.rfftn(image) * np.asarray(response, dtype=np.float32)
        filtered = np.fft.irfftn(filtered_fft, s=image.shape).real
        return np.asarray(filtered, dtype=np.float32)

    if mode_normalized in {"gaussian_subtract", "gaussian-subtract", "gaussian_real"}:
        try:
            from scipy.ndimage import gaussian_filter
        except Exception as exc:
            raise RuntimeError(
                "--highpass-mode gaussian_subtract requires SciPy. Install it with: pip install scipy"
            ) from exc
        sigma_A = math.sqrt(math.log(2.0)) / (math.sqrt(2.0) * math.pi * cutoff)
        sigma_px = sigma_A / float(pixel_size_A)
        if sigma_px <= 0.0:
            return image
        lowpassed = gaussian_filter(image, sigma=float(sigma_px), mode="reflect")
        return np.asarray(image - lowpassed, dtype=np.float32)

    raise ValueError(
        f"Unsupported high-pass mode '{mode}'. Expected one of: cosine, gaussian_fft, gaussian_subtract"
    )


def connect_cryosparc(instance_info_path: str):
    from cryosparc.tools import CryoSPARC

    info_path = Path(instance_info_path).expanduser()
    if not info_path.exists():
        raise RuntimeError(
            f"Could not find CryoSPARC instance info at {info_path}.\n"
            "Pass --instance-info /path/to/instance_info.json or create that file.\n"
            "Example:\n"
            "  python3 consensus_denoise.py P3 W2 J101 J102 --instance-info /path/to/instance_info.json\n"
            "Expected JSON format:\n"
            "{\n"
            '    "license": "YOUR_LICENSE_ID",\n'
            '    "email": "user@example.com",\n'
            '    "password": "YOUR_PASSWORD",\n'
            '    "base_port": 39000,\n'
            '    "host": "YOUR_CRYOSPARC_HOST"\n'
            "}\n"
            "The license value can be found in the config.sh file under your cryosparc2_master directory."
        )

    try:
        data = json.loads(info_path.read_text())
    except Exception as exc:
        raise RuntimeError(f"Failed to read CryoSPARC instance info from {info_path}") from exc

    try:
        cs = CryoSPARC(**data)
    except Exception as exc:
        raise RuntimeError(f"Failed to authenticate using instance info {info_path}") from exc

    if not cs.test_connection():
        raise RuntimeError(f"Could not connect to CryoSPARC using instance info {info_path}")
    return cs, f"instance info {info_path}"


def infer_project_dir(project, override: Optional[str]) -> Path:
    if override:
        project_dir = Path(override).expanduser().resolve()
        if not project_dir.exists():
            raise FileNotFoundError(f"--project-dir does not exist: {project_dir}")
        return project_dir

    for attr_name in ("dir", "project_dir", "path"):
        attr = getattr(project, attr_name, None)
        if attr is None:
            continue
        if callable(attr):
            with warnings.catch_warnings():
                warnings.filterwarnings("ignore", category=DeprecationWarning)
                try:
                    value = attr()
                except TypeError:
                    continue
        else:
            value = attr
        if value:
            project_dir = Path(str(value)).expanduser().resolve()
            if project_dir.exists():
                return project_dir

    raise RuntimeError(
        "Could not infer the CryoSPARC project directory from cryosparc-tools. "
        "Please provide --project-dir explicitly."
    )


def resolve_project_path(project_dir: Path, stored_path: str) -> Path:
    path = Path(normalize_text(stored_path)).expanduser()
    return path if path.is_absolute() else (project_dir / path)


def endpoint_preference(name: str, preferred_names: Sequence[str]) -> Tuple[int, str]:
    normalized = normalize_text(name)
    try:
        index = list(preferred_names).index(normalized)
    except ValueError:
        index = len(preferred_names)
    return (index, normalized)


def looks_like_job_uid(text: str) -> bool:
    return re.fullmatch(r"[Jj]?\d+", normalize_text(text).strip()) is not None


def parse_job_output_reference(text: str) -> Tuple[str, Optional[str]]:
    raw = normalize_text(text).strip()
    if ":" in raw:
        job_text, output_name = raw.split(":", 1)
        return ensure_prefix(job_text.strip(), "J"), normalize_text(output_name).strip() or None
    if not looks_like_job_uid(raw):
        raise ValueError(
            f"Invalid source reference '{text}'. Expected J### or J###:output_name."
        )
    return ensure_prefix(raw, "J"), None


def load_output_group(job, group_name: str, purpose: str):
    try:
        return job.load_output(group_name)
    except Exception as exc:
        raise RuntimeError(
            f"Could not load {purpose} output group '{group_name}' from {job.project_uid}/{job.uid}"
        ) from exc


def validate_micrographs(dataset, slot_name: str) -> None:
    require_field(dataset, "uid")
    require_field(dataset, f"{slot_name}/path")


def pick_denoised_slot(dataset, explicit_slot: Optional[str]) -> str:
    if explicit_slot:
        require_field(dataset, f"{explicit_slot}/path")
        return normalize_text(explicit_slot)

    if existing_field(dataset, f"{DEFAULT_DENOISED_SLOT}/path"):
        return DEFAULT_DENOISED_SLOT

    slot_names = sorted(
        prefix
        for prefix in dataset.prefixes()
        if prefix != "uid" and existing_field(dataset, f"{prefix}/path")
    )
    denoised_slots = [slot for slot in slot_names if "denois" in normalize_text(slot).lower()]
    if len(denoised_slots) == 1:
        return denoised_slots[0]
    if len(denoised_slots) > 1:
        candidate_text = ", ".join(denoised_slots)
        raise RuntimeError(
            f"Multiple denoised-like slots were found: {candidate_text}. "
            "Pass --denoised-slot explicitly."
        )
    available_text = ", ".join(slot_names) if slot_names else "(none)"
    raise RuntimeError(
        f"Could not auto-detect a denoised slot. Available path-bearing slots: {available_text}. "
        f"Tried default '{DEFAULT_DENOISED_SLOT}' first. Pass --denoised-slot explicitly."
    )


def select_source_dataset(job, explicit_output_name: Optional[str], explicit_slot: Optional[str]) -> Tuple[str, object, str]:
    preferred = ("micrographs", "exposures", "movies")
    exposure_output_names = [
        normalize_text(name)
        for name, output_spec in (getattr(job, "outputs", {}) or {}).items()
        if normalize_text(getattr(output_spec, "type", "")) == "exposure"
    ]
    candidate_names = [normalize_text(explicit_output_name)] if explicit_output_name else sorted(
        exposure_output_names,
        key=lambda value: endpoint_preference(value, preferred),
    )

    available_text = ", ".join(exposure_output_names) if exposure_output_names else "(none)"
    errors: List[str] = []
    for name in candidate_names:
        try:
            dataset = load_output_group(job, name, "micrograph")
            slot_name = pick_denoised_slot(dataset, explicit_slot)
            validate_micrographs(dataset, slot_name)
            return name, dataset, slot_name
        except Exception as exc:
            errors.append(f"{name}: {exc}")

    if explicit_output_name:
        raise RuntimeError(
            f"Could not load a usable exposure output '{explicit_output_name}' from {job.project_uid}/{job.uid}. "
            f"Available exposure outputs: {available_text}. "
            f"Tried: {'; '.join(errors) if errors else 'none'}"
        )

    raise RuntimeError(
        f"Could not auto-detect a usable exposure output on {job.project_uid}/{job.uid}. "
        f"Available exposure outputs: {available_text}. "
        f"Tried: {'; '.join(errors) if errors else 'none'}"
    )


def build_uid_row_lookup(dataset, label: str) -> Dict[int, int]:
    uids = np.asarray(array_copy(dataset, "uid")).reshape(-1)
    lookup: Dict[int, int] = {}
    for index, value in enumerate(uids.tolist()):
        uid = int(value)
        if uid in lookup:
            raise RuntimeError(f"Duplicate micrograph uid={uid} found in {label}")
        lookup[uid] = index
    return lookup


def validate_matching_uid_sets(reference: SourceDataset, other: SourceDataset) -> None:
    reference_uids = set(reference.uid_to_row)
    other_uids = set(other.uid_to_row)
    if reference_uids == other_uids:
        return

    missing = sorted(reference_uids - other_uids)
    extra = sorted(other_uids - reference_uids)

    def preview(values: Sequence[int]) -> str:
        if not values:
            return "(none)"
        shown = ", ".join(str(value) for value in values[:5])
        suffix = "" if len(values) <= 5 else ", ..."
        return shown + suffix

    raise RuntimeError(
        f"Source UID mismatch between {reference.label} and {other.label}. "
        f"Missing from {other.job_uid}: {preview(missing)}. "
        f"Extra on {other.job_uid}: {preview(extra)}."
    )


def output_slots_from_spec(job, output_name: str, dataset) -> List[str]:
    output_spec = job.outputs[output_name]
    for attr_name in ("slots", "result_slots"):
        value = getattr(output_spec, attr_name, None)
        if not value:
            continue
        slots: List[str] = []
        for item in value:
            slot_name = getattr(item, "name", item)
            normalized = normalize_text(slot_name).strip()
            if normalized and normalized != "uid":
                slots.append(normalized)
        if slots:
            return sorted(dict.fromkeys(slots))

    prefix_set = set(dataset.prefixes())
    fallback_slots = [
        prefix
        for prefix in sorted(prefix_set)
        if prefix != "uid" and existing_field(dataset, f"{prefix}/path")
    ]
    for slot_name in ("ctf", "ctf_stats", "mscope_params"):
        if slot_name in prefix_set:
            fallback_slots.append(slot_name)
    return sorted(dict.fromkeys(fallback_slots))


def normalize_shape_tuple(raw_shape) -> Optional[Tuple[int, int]]:
    if raw_shape is None:
        return None
    values = np.asarray(raw_shape).reshape(-1).tolist()
    if not values:
        return None
    shape = tuple(int(value) for value in values)
    if len(shape) == 2:
        return shape
    if len(shape) == 3 and int(shape[0]) == 1:
        return (int(shape[1]), int(shape[2]))
    return None


def build_output_path(job_uid: str, output_subdir: str, input_path: str, micrograph_uid: int) -> Tuple[PurePosixPath, str]:
    basename = f"{Path(str(input_path)).stem}_uid{micrograph_uid}_consensus_denoised.mrc"
    rel_path = PurePosixPath(job_uid) / output_subdir / basename
    return rel_path, str(rel_path)


def prepare_source(source: SourceDataset) -> PreparedSource:
    dataset = source.dataset
    return PreparedSource(
        label=source.label,
        slot_name=source.slot_name,
        uid_to_row=source.uid_to_row,
        paths=[normalize_text(path) for path in array_copy(dataset, f"{source.slot_name}/path")],
        idxs=(
            np.asarray(array_copy(dataset, f"{source.slot_name}/idx"), dtype=np.int64)
            if existing_field(dataset, f"{source.slot_name}/idx")
            else None
        ),
        shapes=(
            np.array(dataset[f"{source.slot_name}/shape"], copy=True)
            if existing_field(dataset, f"{source.slot_name}/shape")
            else None
        ),
        slot_psizes=(
            np.asarray(array_copy(dataset, f"{source.slot_name}/psize_A"), dtype=np.float32)
            if existing_field(dataset, f"{source.slot_name}/psize_A")
            else None
        ),
        mscope_psizes=(
            np.asarray(array_copy(dataset, "mscope_params/psize_A"), dtype=np.float32)
            if existing_field(dataset, "mscope_params/psize_A")
            else None
        ),
    )


def infer_slot_pixel_size_A_prepared(source: PreparedSource, row_index: int, file_psize_A: Optional[float]) -> float:
    if source.slot_psizes is not None:
        value = float(source.slot_psizes[row_index])
        if np.isfinite(value) and value > 0:
            return value
    if source.mscope_psizes is not None:
        value = float(source.mscope_psizes[row_index])
        if np.isfinite(value) and value > 0:
            return value
    if file_psize_A is not None:
        value = float(file_psize_A)
        if np.isfinite(value) and value > 0:
            return value
    return float("nan")


def validate_prepared_shape(source: PreparedSource, row_index: int, image_shape: Tuple[int, int], micrograph_uid: int) -> None:
    if source.shapes is None:
        return
    expected_shape = normalize_shape_tuple(source.shapes[row_index])
    if expected_shape is None:
        return
    if tuple(int(value) for value in image_shape) != expected_shape:
        raise RuntimeError(
            f"Image shape mismatch for {source.label} uid={micrograph_uid}: "
            f"file={tuple(int(value) for value in image_shape)}, dataset={expected_shape}"
        )


def process_micrograph(
    *,
    output_index: int,
    micrograph_uid: int,
    prepared_sources: Sequence[PreparedSource],
    project_dir: Path,
    external_job_uid: str,
    output_subdir: str,
    naming_path: str,
    highpass_resolution_A: Optional[float],
    highpass_mode: str,
    clahe_enabled: bool,
    clahe_clip_limit: float,
    clahe_kernel_size: Optional[int],
) -> ProcessedMicrograph:
    combined_image: Optional[np.ndarray] = None
    combined_psize_A: Optional[float] = None

    for source in prepared_sources:
        row_index = source.uid_to_row[micrograph_uid]
        stored_path = source.paths[row_index]
        if not stored_path:
            raise RuntimeError(f"Empty path for uid={micrograph_uid} on {source.label}")

        source_path = resolve_project_path(project_dir, stored_path)
        if source_path.is_dir():
            raise RuntimeError(f"Expected an MRC file for uid={micrograph_uid}, got directory: {source_path}")

        stack_index = int(source.idxs[row_index]) if source.idxs is not None else 0
        image, file_psize_A = read_mrc_image(source_path, stack_index=stack_index)
        validate_prepared_shape(source, row_index, tuple(image.shape), micrograph_uid)

        pixel_size_A = infer_slot_pixel_size_A_prepared(source, row_index, file_psize_A)
        if not np.isfinite(pixel_size_A) or float(pixel_size_A) <= 0:
            raise RuntimeError(
                f"Could not determine a valid pixel size for uid={micrograph_uid} from {source.label}"
            )
        if highpass_resolution_A is not None:
            image = smooth_highpass_filter(
                image,
                pixel_size_A=float(pixel_size_A),
                resolution_A=float(highpass_resolution_A),
                mode=str(highpass_mode),
            )

        if combined_image is None:
            combined_image = image
            combined_psize_A = float(pixel_size_A)
        else:
            if tuple(combined_image.shape) != tuple(image.shape):
                raise RuntimeError(
                    f"Shape mismatch for uid={micrograph_uid}: first source has {combined_image.shape}, "
                    f"but {source.label} has {image.shape}"
                )
            if combined_psize_A is not None and abs(float(pixel_size_A) - float(combined_psize_A)) > 1e-4:
                raise RuntimeError(
                    f"Pixel size mismatch for uid={micrograph_uid}: first source has {combined_psize_A:.6f} A, "
                    f"but {source.label} has {float(pixel_size_A):.6f} A"
                )
            np.minimum(combined_image, image, out=combined_image)

    if combined_image is None or combined_psize_A is None:
        raise RuntimeError(f"No source images were loaded for uid={micrograph_uid}")

    if clahe_enabled:
        combined_image = apply_clahe(
            combined_image,
            clip_limit=float(clahe_clip_limit),
            kernel_size=clahe_kernel_size,
        )

    output_rel_path_obj, output_rel_path = build_output_path(
        external_job_uid,
        output_subdir,
        naming_path,
        micrograph_uid,
    )
    write_mrc(project_dir / output_rel_path_obj, combined_image, combined_psize_A)
    return ProcessedMicrograph(
        output_index=output_index,
        output_rel_path=output_rel_path,
        combined_shape=tuple(int(v) for v in combined_image.shape),
        combined_psize_A=float(combined_psize_A),
        combined_vmin=float(np.min(combined_image)),
        combined_vmax=float(np.max(combined_image)),
        preview_image=np.array(combined_image, copy=True) if int(output_index) == 0 else None,
    )


def build_output_dataset(
    reference_dataset,
    slot_name: str,
    paths: Sequence[str],
    idxs: Optional[np.ndarray],
    formats: Optional[np.ndarray],
    vmins: Optional[np.ndarray],
    vmaxs: Optional[np.ndarray],
    shapes: Optional[np.ndarray],
    psizes: Optional[np.ndarray],
):
    row_count = len(reference_dataset["uid"])
    dataset = reference_dataset.take(np.arange(int(row_count), dtype=np.int64))
    dataset[f"{slot_name}/path"] = np.asarray(paths, dtype=object)
    if idxs is not None and existing_field(dataset, f"{slot_name}/idx"):
        dataset[f"{slot_name}/idx"] = np.asarray(idxs, dtype=idxs.dtype)
    if formats is not None and existing_field(dataset, f"{slot_name}/format"):
        dataset[f"{slot_name}/format"] = np.asarray(formats, dtype=formats.dtype)
    if vmins is not None and existing_field(dataset, f"{slot_name}/vmin"):
        dataset[f"{slot_name}/vmin"] = np.asarray(vmins, dtype=vmins.dtype)
    if vmaxs is not None and existing_field(dataset, f"{slot_name}/vmax"):
        dataset[f"{slot_name}/vmax"] = np.asarray(vmaxs, dtype=vmaxs.dtype)
    if shapes is not None and existing_field(dataset, f"{slot_name}/shape"):
        dataset[f"{slot_name}/shape"] = np.asarray(shapes, dtype=shapes.dtype)
    if psizes is not None and existing_field(dataset, f"{slot_name}/psize_A"):
        dataset[f"{slot_name}/psize_A"] = np.asarray(psizes, dtype=psizes.dtype)
    return dataset


def format_duration_hms(total_seconds: float) -> str:
    total_seconds = max(0, int(round(float(total_seconds))))
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    if hours:
        return f"{hours:d}h {minutes:02d}m {seconds:02d}s"
    if minutes:
        return f"{minutes:d}m {seconds:02d}s"
    return f"{seconds:d}s"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        formatter_class=HelpFormatter,
        description=(
            "Combine denoised micrographs from matching CryoSPARC exposure outputs by taking the "
            "pixelwise minimum across the source denoised images."
        ),
        epilog=(
            "Examples:\n"
            "  python3 consensus_denoise.py P3 W2 J101 J102 J103\n"
            "  python3 consensus_denoise.py P3 W2 J101:micrographs J102:micrographs\n"
            f"  python3 consensus_denoise.py P3 W2 J101 J102 --denoised-slot {DEFAULT_DENOISED_SLOT}\n"
            "  python3 consensus_denoise.py P3 W2 J101 J102 J103 --workers 4\n"
            "  python3 consensus_denoise.py P3 W2 J101 J102 --highpass\n"
            "  python3 consensus_denoise.py P3 W2 J101 J102 --highpass 300"
        ),
    )
    parser.add_argument("project_uid", help="Project UID, e.g. P3")
    parser.add_argument("workspace_uid", help="Workspace UID for the new External job, e.g. W2")
    parser.add_argument(
        "sources",
        nargs="+",
        help="Source denoising jobs as J### or J###:output_name; the first source is the passthrough reference",
    )
    parser.add_argument(
        "--micrographs-group",
        default=None,
        help="Exposure output group to use when a source is given as J### without :output_name",
    )
    parser.add_argument(
        "--denoised-slot",
        default=None,
        help=(
            f"Slot to read from every source exposure output; defaults to '{DEFAULT_DENOISED_SLOT}' "
            "when present, otherwise auto-detects a unique denoised-like slot"
        ),
    )
    parser.add_argument(
        "--output-denoised-slot",
        default=None,
        help="Slot to overwrite in the derived output; defaults to the reference source slot",
    )
    parser.add_argument(
        "--output-name",
        default="micrographs_consensus_denoised",
        help="Name of the derived exposure output group",
    )
    parser.add_argument(
        "--output-subdir",
        default="consensus_denoised_micrographs",
        help="Subdirectory under the External job directory where output MRCs are written",
    )
    parser.add_argument(
        "--title",
        default="Consensus denoised micrographs",
        help="Base title for the created External job; runtime options are appended automatically",
    )
    parser.add_argument(
        "--description",
        default="",
        help="Optional additional markdown description text to append to the generated job description",
    )
    parser.add_argument(
        "--instance-info",
        default=str(Path.home() / "instance_info.json"),
        help="Path to CryoSPARC instance_info.json",
    )
    parser.add_argument(
        "--project-dir",
        default=None,
        help="Explicit CryoSPARC project directory if cryosparc-tools cannot infer it",
    )
    parser.add_argument(
        "--progress-every",
        type=int,
        default=25,
        help="Log progress every N micrographs; use 0 to suppress periodic progress logs",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=1,
        help=(
            "How many micrographs to process concurrently. "
            "Values like 2-4 can help on fast local storage for large runs."
        ),
    )
    parser.add_argument(
        "--highpass",
        type=float,
        nargs="?",
        const=200.0,
        default=None,
        help=(
            "Optional high-pass filter resolution in Angstrom, applied before the pixelwise minimum. "
            "If provided without a value, defaults to 200 A. If omitted, no high-pass filter is applied."
        ),
    )
    parser.add_argument(
        "--highpass-mode",
        choices=["cosine", "gaussian_fft", "gaussian_subtract"],
        default="gaussian_fft",
        help=(
            "High-pass filter shape to apply before the pixelwise minimum. "
            "'gaussian_fft' is the default Gaussian high-pass in Fourier space; 'cosine' is the raised-cosine FFT filter; "
            "'gaussian_subtract' subtracts a Gaussian-blurred real-space image."
        ),
    )
    parser.add_argument(
        "--clahe",
        action="store_true",
        help="Apply optional CLAHE to the final consensus MRC after consensus and high-pass filtering",
    )
    parser.add_argument(
        "--clahe-clip-limit",
        type=float,
        default=0.01,
        help="CLAHE clip limit passed to skimage.exposure.equalize_adapthist",
    )
    parser.add_argument(
        "--clahe-kernel-size",
        type=int,
        default=None,
        help="Optional CLAHE kernel size in pixels; default uses an automatic tile size",
    )

    args = parser.parse_args()

    args.project_uid = ensure_prefix(args.project_uid, "P")
    args.workspace_uid = ensure_prefix(args.workspace_uid, "W")
    if not args.sources:
        parser.error("At least one source job is required")
    if args.progress_every is not None and args.progress_every < 0:
        parser.error("--progress-every must be >= 0")
    if args.workers < 1:
        parser.error("--workers must be >= 1")
    if args.highpass is not None and args.highpass <= 0:
        parser.error("--highpass must be > 0")
    if args.clahe_clip_limit <= 0:
        parser.error("--clahe-clip-limit must be > 0")
    if args.clahe_kernel_size is not None and args.clahe_kernel_size <= 0:
        parser.error("--clahe-kernel-size must be > 0")
    return args


def main() -> None:
    args = parse_args()
    check_runtime_dependencies(args)

    cs, auth_source = connect_cryosparc(args.instance_info)
    project = cs.find_project(args.project_uid)
    project_dir = infer_project_dir(project, args.project_dir)

    loaded_sources: List[SourceDataset] = []
    reference_job = None
    reference_dataset = None
    reference_output_name = None
    output_slot_name = None

    for source_text in args.sources:
        job_uid, explicit_output_name = parse_job_output_reference(source_text)
        if explicit_output_name is None:
            explicit_output_name = args.micrographs_group

        job = project.find_job(job_uid)
        output_name, dataset, slot_name = select_source_dataset(
            job,
            explicit_output_name=explicit_output_name,
            explicit_slot=args.denoised_slot,
        )
        source = SourceDataset(
            job_uid=job_uid,
            output_name=output_name,
            slot_name=slot_name,
            dataset=dataset,
            uid_to_row=build_uid_row_lookup(dataset, f"{job.project_uid}/{job.uid}:{output_name}"),
        )

        if not loaded_sources:
            reference_job = job
            reference_dataset = dataset
            reference_output_name = output_name
            output_slot_name = normalize_text(args.output_denoised_slot or slot_name)
            require_field(reference_dataset, f"{output_slot_name}/path")
        else:
            validate_matching_uid_sets(loaded_sources[0], source)

        loaded_sources.append(source)

    assert reference_job is not None
    assert reference_dataset is not None
    assert reference_output_name is not None
    assert output_slot_name is not None

    reference_source = loaded_sources[0]
    prepared_sources = [prepare_source(source) for source in loaded_sources]
    micrograph_uids = np.asarray(array_copy(reference_dataset, "uid")).reshape(-1)
    micrograph_count = int(micrograph_uids.size)

    job_title = build_job_title(args.title, len(loaded_sources), args.highpass, args.highpass_mode, args.clahe, args.clahe_clip_limit)
    job_desc = build_job_description(args, prepared_sources, reference_source, output_slot_name, micrograph_count)
    if normalize_text(args.description).strip():
        job_desc = f"{job_desc}\n\n{normalize_text(args.description).strip()}"

    reference_input_slots = output_slots_from_spec(reference_job, reference_output_name, reference_dataset)
    external_job = project.create_external_job(workspace_uid=args.workspace_uid, title=job_title, desc=job_desc)
    external_job.add_input(type="exposure", name="reference_micrographs", slots=reference_input_slots)
    external_job.connect(
        target_input="reference_micrographs",
        source_job_uid=reference_source.job_uid,
        source_output=reference_source.output_name,
    )

    for source_index, source in enumerate(loaded_sources[1:], start=2):
        input_name = f"source_micrographs_{source_index}"
        external_job.add_input(type="exposure", name=input_name, slots=[source.slot_name])
        external_job.connect(
            target_input=input_name,
            source_job_uid=source.job_uid,
            source_output=source.output_name,
        )

    external_job.add_output(
        type="exposure",
        name=args.output_name,
        passthrough="reference_micrographs",
        slots=[output_slot_name],
        alloc=reference_dataset,
    )

    output_dir = project_dir / external_job.uid / args.output_subdir
    output_dir.mkdir(parents=True, exist_ok=True)

    output_paths = [normalize_text(path) for path in array_copy(reference_dataset, f"{output_slot_name}/path")]
    output_idxs = (
        np.asarray(array_copy(reference_dataset, f"{output_slot_name}/idx"), dtype=np.uint32)
        if existing_field(reference_dataset, f"{output_slot_name}/idx")
        else None
    )
    output_formats = (
        np.array(reference_dataset[f"{output_slot_name}/format"], copy=True)
        if existing_field(reference_dataset, f"{output_slot_name}/format")
        else None
    )
    output_vmins = (
        np.asarray(array_copy(reference_dataset, f"{output_slot_name}/vmin"), dtype=np.float32)
        if existing_field(reference_dataset, f"{output_slot_name}/vmin")
        else None
    )
    output_vmaxs = (
        np.asarray(array_copy(reference_dataset, f"{output_slot_name}/vmax"), dtype=np.float32)
        if existing_field(reference_dataset, f"{output_slot_name}/vmax")
        else None
    )
    output_shapes = (
        np.array(reference_dataset[f"{output_slot_name}/shape"], copy=True)
        if existing_field(reference_dataset, f"{output_slot_name}/shape")
        else None
    )
    output_psizes = (
        np.asarray(array_copy(reference_dataset, f"{output_slot_name}/psize_A"), dtype=np.float32)
        if existing_field(reference_dataset, f"{output_slot_name}/psize_A")
        else None
    )
    reference_slot_paths = [normalize_text(path) for path in array_copy(reference_dataset, f"{output_slot_name}/path")]
    fallback_reference_paths = prepared_sources[0].paths
    naming_paths = [
        reference_slot_paths[index] or fallback_reference_paths[index] or f"uid{int(micrograph_uids[index])}"
        for index in range(micrograph_count)
    ]

    progress_every = None if int(args.progress_every) == 0 else max(1, int(args.progress_every))
    if progress_every is not None and micrograph_count <= 10:
        progress_every = 1
    worker_count = int(args.workers)

    start_time = time.perf_counter()
    with external_job.run():
        external_job.log(f"Auth source: {auth_source}")
        external_job.log(f"Project dir: {project_dir}")
        external_job.log(
            f"Reference source: {args.project_uid}/{reference_source.job_uid}:{reference_source.output_name} "
            f"slot '{reference_source.slot_name}'"
        )
        if len(loaded_sources) == 1:
            external_job.log("Only one source was provided; the output will be a rewritten copy of that denoised slot.")
        for source_index, source in enumerate(loaded_sources, start=1):
            external_job.log(
                f"Source {source_index}: {args.project_uid}/{source.job_uid}:{source.output_name} "
                f"slot '{source.slot_name}'"
            )
        external_job.log(f"Job title: {job_title}")
        external_job.log("Job description:\n" + job_desc)
        external_job.log(f"Output slot: '{output_slot_name}'")
        external_job.log(f"Micrographs: {micrograph_count:,}")
        external_job.log(f"Workers: {worker_count}")
        if args.highpass is not None:
            external_job.log(
                f"High-pass filter: {float(args.highpass):g} A before the pixelwise minimum (mode={args.highpass_mode})"
            )
        if args.clahe:
            external_job.log(
                f"CLAHE: enabled after consensus (clip_limit={float(args.clahe_clip_limit):g}, kernel_size={args.clahe_kernel_size if args.clahe_kernel_size else 'auto'})"
            )
        else:
            external_job.log("High-pass filter: disabled")
        external_job.log(f"Arguments: {vars(args)}")
        processed_count = 0
        preview_logged = False

        def record_result(result: ProcessedMicrograph) -> None:
            nonlocal preview_logged
            output_index = int(result.output_index)
            output_paths[output_index] = result.output_rel_path
            if output_idxs is not None:
                output_idxs[output_index] = np.uint32(0)
            if output_formats is not None:
                current_value = output_formats[output_index]
                if not normalize_text(current_value).strip():
                    output_formats[output_index] = "MRC"
            if output_vmins is not None:
                output_vmins[output_index] = np.float32(result.combined_vmin)
            if output_vmaxs is not None:
                output_vmaxs[output_index] = np.float32(result.combined_vmax)
            if output_shapes is not None:
                output_shapes[output_index] = np.asarray(result.combined_shape, dtype=output_shapes.dtype)
            if output_psizes is not None:
                output_psizes[output_index] = np.float32(result.combined_psize_A)
            if (not preview_logged) and result.preview_image is not None:
                preview_title = f"First denoised micrograph | uid={int(micrograph_uids[output_index])} | {result.combined_shape[1]}x{result.combined_shape[0]} px"
                try:
                    log_preview_image(external_job, result.preview_image, preview_title)
                    preview_logged = True
                except Exception as exc:
                    external_job.log(f"WARNING: failed to log first-image preview: {exc}")

        def maybe_log_progress(processed_count_local: int) -> None:
            if progress_every is None:
                return
            if not (
                processed_count_local == micrograph_count
                or processed_count_local == 1
                or processed_count_local % progress_every == 0
            ):
                return
            elapsed = time.perf_counter() - start_time
            avg_seconds = elapsed / float(processed_count_local)
            remaining = max(0.0, avg_seconds * float(micrograph_count - processed_count_local))
            external_job.log(
                f"Processed {processed_count_local:,}/{micrograph_count:,} micrographs "
                f"(elapsed {format_duration_hms(elapsed)}, ETA {format_duration_hms(remaining)})"
            )

        if worker_count == 1:
            for output_index, raw_uid in enumerate(micrograph_uids.tolist()):
                result = process_micrograph(
                    output_index=output_index,
                    micrograph_uid=int(raw_uid),
                    prepared_sources=prepared_sources,
                    project_dir=project_dir,
                    external_job_uid=external_job.uid,
                    output_subdir=args.output_subdir,
                    naming_path=naming_paths[output_index],
                    highpass_resolution_A=args.highpass,
                    highpass_mode=args.highpass_mode,
                    clahe_enabled=args.clahe,
                    clahe_clip_limit=args.clahe_clip_limit,
                    clahe_kernel_size=args.clahe_kernel_size,
                )
                record_result(result)
                processed_count += 1
                maybe_log_progress(processed_count)
        else:
            max_pending = max(worker_count, worker_count * 4)
            next_submit_index = 0
            pending = {}
            with ThreadPoolExecutor(max_workers=worker_count) as executor:
                while next_submit_index < micrograph_count and len(pending) < max_pending:
                    future = executor.submit(
                        process_micrograph,
                        output_index=next_submit_index,
                        micrograph_uid=int(micrograph_uids[next_submit_index]),
                        prepared_sources=prepared_sources,
                        project_dir=project_dir,
                        external_job_uid=external_job.uid,
                        output_subdir=args.output_subdir,
                        naming_path=naming_paths[next_submit_index],
                        highpass_resolution_A=args.highpass,
                        highpass_mode=args.highpass_mode,
                        clahe_enabled=args.clahe,
                        clahe_clip_limit=args.clahe_clip_limit,
                        clahe_kernel_size=args.clahe_kernel_size,
                    )
                    pending[future] = next_submit_index
                    next_submit_index += 1

                while pending:
                    done, _ = wait(tuple(pending.keys()), return_when=FIRST_COMPLETED)
                    for future in done:
                        pending.pop(future, None)
                        result = future.result()
                        record_result(result)
                        processed_count += 1
                        maybe_log_progress(processed_count)
                    while next_submit_index < micrograph_count and len(pending) < max_pending:
                        future = executor.submit(
                            process_micrograph,
                            output_index=next_submit_index,
                            micrograph_uid=int(micrograph_uids[next_submit_index]),
                            prepared_sources=prepared_sources,
                            project_dir=project_dir,
                            external_job_uid=external_job.uid,
                            output_subdir=args.output_subdir,
                            naming_path=naming_paths[next_submit_index],
                            highpass_resolution_A=args.highpass,
                            highpass_mode=args.highpass_mode,
                            clahe_enabled=args.clahe,
                            clahe_clip_limit=args.clahe_clip_limit,
                            clahe_kernel_size=args.clahe_kernel_size,
                        )
                        pending[future] = next_submit_index
                        next_submit_index += 1

        output_dataset = build_output_dataset(
            reference_dataset=reference_dataset,
            slot_name=output_slot_name,
            paths=output_paths,
            idxs=output_idxs,
            formats=output_formats,
            vmins=output_vmins,
            vmaxs=output_vmaxs,
            shapes=output_shapes,
            psizes=output_psizes,
        )
        external_job.save_output(args.output_name, output_dataset)
        total_elapsed = time.perf_counter() - start_time
        external_job.log(
            f"Saved output {args.project_uid}/{external_job.uid}:{args.output_name} "
            f"after {format_duration_hms(total_elapsed)}"
        )

    print(f"Saved output to {args.project_uid}/{external_job.uid}:{args.output_name}")


if __name__ == "__main__":
    main()
